name: Scheduled Merge Remote Action

on: 
  schedule:
    - cron: '0 0 * * *'
    # scheduled for 00:00 every day

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 0 
      - name: Merge Upstream
        uses: Andrey1994/sync-upstream-repo@0.0.2
        with:
          upstream_repo: https://github.com/spack/spack
          upstream_branch: develop
          downstream_branch: develop
          token: ${{ secrets.TOKEN }}
  merge-upstream-intel:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: intel-develop
          fetch-depth: 0 
      - name: Merge Upstream
        uses: Andrey1994/sync-upstream-repo@0.0.2
        with:
          upstream_repo: https://github.com/spack/spack
          upstream_branch: develop
          downstream_branch: intel-develop
          token: ${{ secrets.TOKEN }}

