name: Manual Merge Remote Action

on:
  workflow_dispatch:
    inputs:
      upstream:
        description: 'Upstream repository owner/name. Eg. spack/spack'
        required: true
        default: 'https://github.com/spack/spack'
      upstreambranch:
        description: 'Upstream branch to merge from. Eg. master'
        required: true
        default: 'develop'
      branch:
        description: 'Branch to merge to'
        required: true
        default: 'develop'

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0 
      - name: Merge Upstream
        uses: rovast/sync-upstream-repo@v0.0.1
        with:
          upstream_repo: ${{ github.event.inputs.upstream }}
          upstream_branch: ${{ github.event.inputs.upstreambranch }}
          downstream_branch: ${{ github.event.inputs.branch }}
          token: ${{ secrets.TOKEN }}
